### PR TITLE
Introduce execution stages

### PR DESCRIPTION
**Pull request by ccronca**
Integrate multiple executions stages. This is mainly a port of the official implementation:
https://github.com/comeara/pillar/commit/4d1c8b6cff0107b034b2a27ea2c0b7bef16a9a7e

### CODE REVIEW

**Comment by el-dom** [comment]
@lichtsprung lgtm. Any remarks?

**Comment by lichtsprung** [comment]
@el-dom nope. no remarks. lgtm.

**Comment by ccronca** [comment]
@lichtsprung, any idea when can it be merged ?

**Comment by lichtsprung** [comment]
my bad. Forgot to click on merge. 
I'm on my phone right now. I'll merge it tomorrow!

**Pull request merged**
